name: flutter_application_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.4.0 # Library untuk http connection
  pretty_dio_logger: ^1.3.1 # Logging Http connection
  get_storage: ^2.1.1 # Untuk get storage
  get_cli: ^1.8.4
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

